ec2: Prevent "InvalidNetworkInterfaceID.NotFound" errors in deleteLingeringLambdaENIs
Previously:

```
--- FAIL: TestAccAWSLambdaFunction_VPC_withInvocation (70.96s)
    testing.go:588: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.

        Error: Error applying: 1 error occurred:
        	* aws_subnet.subnet_for_lambda (destroy): 1 error occurred:
        	* aws_subnet.subnet_for_lambda: Failed to delete Lambda ENIs: Error waiting for ENI (eni-00233276ead620ddf) to become detached: InvalidNetworkInterfaceID.NotFound: The networkInterface ID 'eni-00233276ead620ddf' does not exist
```